// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQu8EromyevrzhGJvdgumxhOfxRUca45o',
    appId: '1:72025732538:web:17361444fa158e2d1f1983',
    messagingSenderId: '72025732538',
    projectId: 'dentocare-da779',
    authDomain: 'dentocare-da779.firebaseapp.com',
    storageBucket: 'dentocare-da779.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbu5A43Z5i2GBkcVWtPhhzz9PokDytp4Q',
    appId: '1:72025732538:android:c3257ee5bf38f5571f1983',
    messagingSenderId: '72025732538',
    projectId: 'dentocare-da779',
    storageBucket: 'dentocare-da779.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbJ7DQqVKFa5OQ5lrScTKHYLNJw4UMgjQ',
    appId: '1:72025732538:ios:6c1602e90605525c1f1983',
    messagingSenderId: '72025732538',
    projectId: 'dentocare-da779',
    storageBucket: 'dentocare-da779.firebasestorage.app',
    iosBundleId: 'com.example.dentocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbJ7DQqVKFa5OQ5lrScTKHYLNJw4UMgjQ',
    appId: '1:72025732538:ios:6c1602e90605525c1f1983',
    messagingSenderId: '72025732538',
    projectId: 'dentocare-da779',
    storageBucket: 'dentocare-da779.firebasestorage.app',
    iosBundleId: 'com.example.dentocare',
  );
}
